export const mockGrievances = [
  {
    id: '1',
    refId: 'UL-2026-0001',
    citizenPhone: '9876543210',
    ward: 'Serilingampally',
    category: 'Drainage Overflow',
    description: 'Severe water overflow in residential area',
    status: 'in-progress',
    createdAt: new Date(Date.now() - 3600000),
    assignedTo: 'Mohammed Imran',
    slaEndAt: new Date(Date.now() + 18000000),
  },
  {
    id: '2',
    refId: 'UL-2026-0002',
    citizenPhone: '9876543211',
    ward: 'Kukatpally',
    category: 'Pothole / Road Damage',
    description: 'Large pothole on main road',
    status: 'assigned',
    createdAt: new Date(Date.now() - 7200000),
    assignedTo: 'Pradeep Yadav',
    slaEndAt: new Date(Date.now() + 14400000),
  },
  {
    id: '3',
    refId: 'UL-2026-0003',
    citizenPhone: '9876543212',
    ward: 'Charminar',
    category: 'Street Light Not Working',
    description: 'Multiple street lights not functioning at night',
    status: 'new',
    createdAt: new Date(Date.now() - 1800000),
    assignedTo: null,
    slaEndAt: new Date(Date.now() + 28800000),
  },
  {
    id: '4',
    refId: 'UL-2026-0004',
    citizenPhone: '9876543213',
    ward: 'Serilingampally',
    category: 'Water Supply Issue',
    description: 'No water supply for 3 days',
    status: 'in-progress',
    createdAt: new Date(Date.now() - 54000000),
    assignedTo: 'Mohammed Imran',
    slaEndAt: new Date(Date.now() - 3600000),
  },
  {
    id: '5',
    refId: 'UL-2026-0005',
    citizenPhone: '9876543214',
    ward: 'LB Nagar',
    category: 'Garbage Not Collected',
    description: 'Garbage pile accumulating in street',
    status: 'assigned',
    createdAt: new Date(Date.now() - 14400000),
    assignedTo: 'N. Srinivas',
    slaEndAt: new Date(Date.now() + 8400000),
  },
  {
    id: '6',
    refId: 'UL-2026-0006',
    citizenPhone: '9876543215',
    ward: 'Secunderabad',
    category: 'Illegal Construction',
    description: 'Unauthorized structure being built',
    status: 'resolved',
    createdAt: new Date(Date.now() - 86400000),
    assignedTo: 'S. Reddy',
    slaEndAt: new Date(Date.now() - 57600000),
  },
  {
    id: '7',
    refId: 'UL-2026-0007',
    citizenPhone: '9876543216',
    ward: 'Jubilee Hills',
    category: 'Pothole / Road Damage',
    description: 'Road surface crumbling',
    status: 'new',
    createdAt: new Date(Date.now() - 3600000),
    assignedTo: null,
    slaEndAt: new Date(Date.now() + 28800000),
  },
  {
    id: '8',
    refId: 'UL-2026-0008',
    citizenPhone: '9876543217',
    ward: 'Mehdipatnam',
    category: 'Drainage Overflow',
    description: 'Clogged drain causing overflow',
    status: 'in-progress',
    createdAt: new Date(Date.now() - 25200000),
    assignedTo: 'Farooq Ahmed',
    slaEndAt: new Date(Date.now() + 5400000),
  },
];

export const mockOfficers = [
  { id: '1', name: 'Rajesh Kumar', ward: 'Charminar', active: 6, resolved: 12, status: 'online' },
  { id: '2', name: 'S. Reddy', ward: 'Secunderabad', active: 3, resolved: 8, status: 'online' },
  { id: '3', name: 'Farooq Ahmed', ward: 'Mehdipatnam', active: 8, resolved: 15, status: 'online' },
  { id: '4', name: 'Kavitha Rao', ward: 'Jubilee Hills', active: 4, resolved: 9, status: 'online' },
  { id: '5', name: 'Pradeep Yadav', ward: 'Kukatpally', active: 7, resolved: 14, status: 'online' },
  { id: '6', name: 'N. Srinivas', ward: 'LB Nagar', active: 5, resolved: 11, status: 'online' },
  { id: '7', name: 'Anjali Sharma', ward: 'Khairatabad', active: 2, resolved: 6, status: 'offline' },
  { id: '8', name: 'Mohammed Imran', ward: 'Serilingampally', active: 9, resolved: 18, status: 'online' },
];

export const wardDistribution = [
  { ward: 'Kukatpally', complaints: 38 },
  { ward: 'Serilingampally', complaints: 42 },
  { ward: 'Charminar', complaints: 19 },
  { ward: 'Secunderabad', complaints: 27 },
  { ward: 'Jubilee Hills', complaints: 11 },
  { ward: 'LB Nagar', complaints: 24 },
  { ward: 'Mehdipatnam', complaints: 17 },
  { ward: 'Khairatabad', complaints: 8 },
];

export const kioskHealthLogs = [
  { timestamp: '10:12 AM', kiosk: 'Kiosk-01', event: 'Offline mode activated', type: 'alert' },
  { timestamp: '10:18 AM', kiosk: 'Kiosk-01', event: '3 grievances stored locally', type: 'info' },
  { timestamp: '10:25 AM', kiosk: 'Kiosk-01', event: 'Sync successful (3 packets)', type: 'success' },
  { timestamp: '11:02 AM', kiosk: 'Kiosk-02', event: 'Battery at 18%', type: 'alert' },
  { timestamp: '12:10 PM', kiosk: 'Kiosk-03', event: 'Heartbeat missed', type: 'critical' },
  { timestamp: '12:14 PM', kiosk: 'Kiosk-03', event: 'Connection restored', type: 'success' },
];

export const kpiMetrics = {
  totalToday: 186,
  pending: 41,
  slaBreaches: 6,
  avgResolutionTime: 17.8,
  kioskUptime: 98.7,
  citizensServed: 164,
};
